name: portfolio
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.11.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  font_awesome_flutter: ^10.1.0
  google_fonts: ^2.3.1
  animate_do: ^2.1.0
  animated_text_kit: ^4.2.1
  #hover_effect: ^0.6.0
  scrollable_positioned_list: ^0.2.3
  url_launcher: ^6.0.20

  sizer: ^2.0.15

  get: ^4.6.1
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_native_splash: ^2.1.3+1


flutter_native_splash:
  color: "#03001e"
  image: "assets/images/splash.png"




flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

