name: portfolio
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.5.0
  google_fonts: ^6.1.0
  animate_do: ^3.1.2
  animated_text_kit: ^4.2.2
  scrollable_positioned_list: ^0.3.8
  url_launcher: ^6.1.14
  flutter_native_splash: ^2.3.3

  #sizer: ^2.0.15
  responsive_sizer: ^3.2.0

  get: ^4.6.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3




flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_native_splash:
  color: "#03001e"
  image: "assets/images/splash.png"